parameters:
    sfynx.circuitbreaker.class: Sfynx\CircuitBreakerBundle\CircuitBreaker\CircuitBreaker
    sfynx.circuitbreaker.storage.class: Sfynx\CircuitBreakerBundle\Storage\JsonStorage

services:
    sfynx.circuitbreaker.storage:
        class: '%sfynx.circuitbreaker.storage.class%'
        public: true
        arguments:
          - "@sfynx.cache.filecache"

    sfynx.circuitbreaker:
        class: '%sfynx.circuitbreaker.class%'
        public: true
        arguments:
          - "@sfynx.circuitbreaker.storage"

